---
resource_registry:
  # yamllint disable rule:line-length
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::OVNMacAddressNetwork: OS::Heat::None
  OS::TripleO::OVNMacAddressPort: OS::Heat::None
  OS::TripleO::Compute::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Compute::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Compute::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Controller::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Controller::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Controller::Ports::IronicPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_ironic.yaml
  OS::TripleO::Networker::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Networker::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Networker::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Services::CeilometerAgentCentral: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-central-container-puppet.yaml
  OS::TripleO::Services::CeilometerAgentNotification: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-notification-container-puppet.yaml
  OS::TripleO::Services::CeilometerAgentIpmi: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-ipmi-container-puppet.yaml
  OS::TripleO::Services::ComputeCeilometerAgent: /usr/share/openstack-tripleo-heat-templates/deployment/ceilometer/ceilometer-agent-compute-container-puppet.yaml
  OS::TripleO::Services::Collectd: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/collectd-container-puppet.yaml
  OS::TripleO::Services::MetricsQdr: /usr/share/openstack-tripleo-heat-templates/deployment/metrics/qdr-container-puppet.yaml
  OS::TripleO::Services::OsloMessagingRpc: /usr/share/openstack-tripleo-heat-templates/deployment/rabbitmq/rabbitmq-messaging-rpc-pacemaker-puppet.yaml
  OS::TripleO::Services::OsloMessagingNotify: /usr/share/openstack-tripleo-heat-templates/deployment/rabbitmq/rabbitmq-messaging-notify-shared-puppet.yaml
  OS::TripleO::Services::HAproxy: /usr/share/openstack-tripleo-heat-templates/deployment/haproxy/haproxy-pacemaker-puppet.yaml
  OS::TripleO::Services::Pacemaker: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/pacemaker-baremetal-puppet.yaml
  OS::TripleO::Services::PacemakerRemote: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/pacemaker-remote-baremetal-puppet.yaml
  OS::TripleO::Services::Clustercheck: /usr/share/openstack-tripleo-heat-templates/deployment/pacemaker/clustercheck-container-puppet.yaml
  OS::TripleO::Services::Redis: /usr/share/openstack-tripleo-heat-templates/deployment/database/redis-pacemaker-puppet.yaml
  OS::TripleO::Services::Rsyslog: /usr/share/openstack-tripleo-heat-templates/deployment/logging/rsyslog-container-puppet.yaml
  OS::TripleO::Services::MySQL: /usr/share/openstack-tripleo-heat-templates/deployment/database/mysql-pacemaker-puppet.yaml
  OS::TripleO::Services::CinderBackup: /usr/share/openstack-tripleo-heat-templates/deployment/cinder/cinder-backup-pacemaker-puppet.yaml
  OS::TripleO::Services::CinderVolume: /usr/share/openstack-tripleo-heat-templates/deployment/cinder/cinder-volume-pacemaker-puppet.yaml
  OS::TripleO::Services::HeatApi: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-container-puppet.yaml
  OS::TripleO::Services::HeatApiCfn: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-cfn-container-puppet.yaml
  OS::TripleO::Services::HeatApiCloudwatch: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-api-cloudwatch-disabled-puppet.yaml
  OS::TripleO::Services::HeatEngine: /usr/share/openstack-tripleo-heat-templates/deployment/heat/heat-engine-container-puppet.yaml
  OS::TripleO::Services::OctaviaApi: /usr/share/openstack-tripleo-heat-templates//deployment/octavia/octavia-api-container-puppet.yaml
  OS::TripleO::Services::OctaviaHousekeeping: /usr/share/openstack-tripleo-heat-templates/deployment/octavia/octavia-housekeeping-container-puppet.yaml
  OS::TripleO::Services::OctaviaHealthManager: /usr/share/openstack-tripleo-heat-templates/deployment/octavia/octavia-health-manager-container-puppet.yaml
  OS::TripleO::Services::OctaviaWorker: /usr/share/openstack-tripleo-heat-templates/deployment/octavia/octavia-worker-container-puppet.yaml
  OS::TripleO::Services::OctaviaDeploymentConfig: /usr/share/openstack-tripleo-heat-templates/deployment/octavia/octavia-deployment-config.yaml
parameter_defaults:
  RedisVirtualFixedIPs:
    - ip_address: 192.168.122.130
      use_neutron: false
  OVNDBsVirtualFixedIPs:
    - ip_address: 192.168.122.131
      use_neutron: false
  ControllerExtraConfig:
    nova::compute::libvirt::services::libvirt_virt_type: qemu
    nova::compute::libvirt::virt_type: qemu
  ComputeExtraConfig:
    nova::compute::libvirt::services::libvirt_virt_type: qemu
    nova::compute::libvirt::virt_type: qemu
  BarbicanSimpleCryptoGlobalDefault: true
  Debug: true
  DockerPuppetDebug: true
  ContainerCli: podman
  ControllerCount: 3
  ComputeCount: 2
  NetworkerCount: 3
  NeutronGlobalPhysnetMtu: 1500
  CinderLVMLoopDeviceSize: 20480
  CloudName: overcloud.localdomain
  CloudNameInternal: overcloud.internalapi.localdomain
  CloudNameStorage: overcloud.storage.localdomain
  CloudNameStorageManagement: overcloud.storagemgmt.localdomain
  CloudNameCtlplane: overcloud.ctlplane.localdomain
  CloudDomain: localdomain
  NetworkConfigWithAnsible: false
  ControllerHostnameFormat: '%stackname%-controller-%index%'
  ComputeHostnameFormat: '%stackname%-compute-%index%'
  NetworkerHostnameFormat: '%stackname%-networker-%index%'
  CtlplaneNetworkAttributes:
    network:
      dns_domain: localdomain
      mtu: 1500
      name: ctlplane
      tags:
        - 192.168.122.0/24
    subnets:
      ctlplane-subnet:
        cidr: 192.168.122.0/24
        dns_nameservers: 192.168.122.10
        gateway_ip: 192.168.122.10
        host_routes: []
        name: ctlplane-subnet
        ip_version: 4
  NeutronFlatNetworks:
    - datacentre
    - ironic
  ControllerParameters:
    NeutronBridgeMappings:
      - datacentre:br-ex
      - ironic:br-baremetal
  NetworkerParameters:
    NeutronBridgeMappings:
      - datacentre:br-ex
  ComputeParameters:
    NeutronBridgeMappings:
      - datacentre:br-ex
  IronicInspectorInterface: br-baremetal
  # Since we need predictable node names to be able to set this paremeter,
  # it a requirement to set the ci-framework parameter cifmw_run_id with
  # this value 'uni01alpha'.
  IronicInspectorSubnets:
    osp-controller-uni01alpha-0:
      - ip_range: 172.20.1.210,172.20.1.219
    osp-controller-uni01alpha-1:
      - ip_range: 172.20.1.220,172.20.1.229
    osp-controller-uni01alpha-2:
      - ip_range: 172.20.1.230,172.20.1.239
  ServiceNetMap:
    IronicApiNetwork: ironic
    IronicNetwork: ironic
    IronicInspectorNetwork: ironic
  IronicCleaningDiskErase: metadata
  NeutronEnableForceMetadata: true
    # This flag enables internal generation of certificates for communication
    # with amphorae. Use OctaviaCaCert, OctaviaCaKey, OctaviaCaKeyPassphrase,
    # OctaviaClient and OctaviaServerCertsKeyPassphrase cert to configure
    # secure production environments.
  OctaviaGenerateCerts: true
